a = "Prabhveer Singh"
print(a.lower())
print(a.upper())
print(a.replace("Singh", "Kaur"))
print(a.capitalize())
print(a.title())
print(a.count("a")) 
print(a.find("veer"))
print(a.index("Singh"))
print(a.isalpha())
print(a.isalnum())
print(a.split(" "))
print(a.startswith("P"))
print(a.endswith("h"))
print(a.center(50, '*'))
print(a.strip())
print(a.swapcase())
print(a.encode())
print(a.partition("Singh"))
print(a.rfind("i"))
print(a.zfill(30))
print(a.format())
print(a.translate(str.maketrans("a", "@")))
print(a.expandtabs())
print(a.rpartition("Singh"))
print(a.ljust(30, '-'))
print(a.rjust(30, '-'))
print(a.splitlines())   
print(a.islower())
print(a.isupper())
print(a.isprintable())
print(a.casefold()) 
print(a.removeprefix("Prabhveer"))
print(a.removesuffix("Singh"))
print(a.encode('utf-8'))
print(a.isdecimal())
print(a.isdigit())
print(a.isnumeric())
print(a.zfill(40))
print(a.translate(str.maketrans({"a": "@", "e": "3"})))
print(a.center(60, '#'))
print(a.lstrip("P"))
print(a.rstrip("h"))
print(a.split("h"))
print(a.count("i"))
print(a.find("x"))
print(a.index("b")) 
print(a.replace(" ", "_"))
print(a.title())
print(a.capitalize())
print(a.upper())
print(a.lower())
print(a.swapcase())
print(a.strip())
print(a.encode())
print(a.partition("Singh"))
print(a.rfind("i"))
print(a.zfill(30))
print(a.format())
print(a.translate(str.maketrans("a", "@")))
print(a.expandtabs())
print(a.rpartition("Singh"))
print(a.ljust(30, '-'))
print(a.rjust(30, '-'))
